[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "travelling_salesman_problem"
version = "0.2.0"
description = "This is an old university project I've refactored for a job interview"
authors = [{ name = "Peter Bowman", email = "bowmanpete123@gmail.com" }]
license = "MIT"
requires-python = ">=3.13.0"
dependencies = [
    "matplotlib>=3.10.6",
 "numpy",
 "pandas>=2.3.2",
]

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = ["ruff", "ty", "debugpy", "pytest", "docformatter", "python-lsp-server"]

# --- PYLSP: LANGUAGE SERVER PATH FIX ---
[tool.pylsp.settings.python.analysis]
extraPaths = [
    ".",
    "./src",
    "./genetic_algorithm_files",
    "./supporting_tools",
]

# --- RUFF: LINTER SOURCE FIX ---
[tool.ruff]
src = ["src", "genetic_algorithm_files", "supporting_tools", "."]
line-length = 120
target-version = "py313"
select = ["E", "F", "W", "I"]

[tool.ty.environment]
root = ["."]

[tool.pytest.ini_options]
pythonpath = ["src", "genetic_algorithm_files", "supporting_tools"]
testpaths = ["tests"]
norecursedirs = [".git", "venv", "docs"]

[tool.docformatter]
line_length = 120
pre_summary_newline = true
post_summary_newline = true
make_summary_multi_line = false
force_wrap = false
use_double_quotes = true
